hh99-Final-Project/bluemoonBE

- src/main/java/com/sparta/bluemoon/exception/Exception.java
- src/main/java/com/sparta/bluemoon/exception/ExceptionHandling.java
> [#11] feat: exeption

- src/main/java/com/sparta/bluemoon/config/GoogleConfigUtils.java
- src/main/java/com/sparta/bluemoon/config/KakaoConfigUtils.java
- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/controller/GoogleLoginController.java
- src/main/java/com/sparta/bluemoon/controller/KakaoLoginController.java
- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/dto/response/CommentResponseDto.java
- src/main/java/com/sparta/bluemoon/repository/ChatMessageRepository.java
- src/main/java/com/sparta/bluemoon/repository/ChatRoomRepository.java
- src/main/java/com/sparta/bluemoon/repository/ChatRoomUserRepository.java
- src/main/java/com/sparta/bluemoon/repository/CommentRepository.java
- src/main/java/com/sparta/bluemoon/repository/PostRepository.java
- src/main/java/com/sparta/bluemoon/repository/UserRepository.java
- src/main/java/com/sparta/bluemoon/security/FormLoginSuccessHandler.java
- src/main/java/com/sparta/bluemoon/security/UserDetailsImpl.java
- src/main/java/com/sparta/bluemoon/security/UserDetailsServiceImpl.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/security/filter/JwtAuthFilter.java
- src/main/java/com/sparta/bluemoon/security/jwt/JwtDecoder.java
- src/main/java/com/sparta/bluemoon/security/jwt/JwtTokenUtils.java
- src/main/java/com/sparta/bluemoon/security/provider/FormLoginAuthProvider.java
- src/main/java/com/sparta/bluemoon/security/provider/JWTAuthProvider.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/CommentService.java
- src/main/java/com/sparta/bluemoon/service/GoogleLoginService.java
- src/main/java/com/sparta/bluemoon/service/KakaoLoginService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
> [#9]feat:소셜로그인

- src/main/java/com/sparta/bluemoon/controller/UserController.java
- src/main/java/com/sparta/bluemoon/domain/User.java
- src/main/java/com/sparta/bluemoon/dto/request/NicknameSignupRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/response/SocialLoginResponseDto.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/service/UserService.java
> [#19]feat:유저의 닉네임 저장

- src/main/java/com/sparta/bluemoon/controller/TemporaryController.java
- src/main/java/com/sparta/bluemoon/domain/Temporary.java
- src/main/java/com/sparta/bluemoon/dto/request/TemporaryRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/response/TemporaryResponseDto.java
- src/main/java/com/sparta/bluemoon/repository/TemporaryRepository.java
- src/main/java/com/sparta/bluemoon/service/TemporaryService.java
> [#17] feat: 임시저장 기능

- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/test/ConfigUtils.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginController.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginService.java
- src/main/resources/templates/index.html
네이버 로그인 기능은 아직 확정된 부분이 아니라 test 패키지에 존재
나의 게시글 조회 기능에서 게시글이 존재하지 않는 경우 예외 처리 추가
> [#24] feat: 네이버로그인 추가, 나의 게시글 조회 기능 수정

- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
랜덤 1개 -> 5개 그냥 보내주는 형식 
페이징 처리 진행전
프론트와 실시간 채팅 테스트를 5개 게시글을 그냥 보내주는 형식으로 변경
> [#4] feat: 상대방의 게시글 불러오는 로직 변경

- src/main/java/com/sparta/bluemoon/domain/User.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/security/filter/JwtAuthFilter.java
- src/main/java/com/sparta/bluemoon/security/provider/JWTAuthProvider.java
- src/main/java/com/sparta/bluemoon/service/GoogleLoginService.java
- src/main/java/com/sparta/bluemoon/service/KakaoLoginService.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginService.java
다른곳에서 로그인을 할 경우 기존에 로그인했던 기기에서 강제로 토큰을 삭제합니다.
> [#27]feat:중복로그인 방지 기능

- .gitignore
- build.gradle
- src/main/java/com/sparta/bluemoon/config/AmazonS3Config.java
- src/main/java/com/sparta/bluemoon/config/EmbeddedRedisConfig.java
- src/main/java/com/sparta/bluemoon/config/RedisConfig.java
- src/main/java/com/sparta/bluemoon/config/WebSockConfig.java
- src/main/java/com/sparta/bluemoon/controller/ChatController.java
- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/controller/TemporaryController.java
- src/main/java/com/sparta/bluemoon/domain/Post.java
- src/main/java/com/sparta/bluemoon/dto/ChatMessageDto.java
- src/main/java/com/sparta/bluemoon/dto/PostDto.java
- src/main/java/com/sparta/bluemoon/dto/PostRequestDto.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/security/filter/JwtAuthFilter.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/service/RedisSubscriber.java
- src/main/java/com/sparta/bluemoon/service/VoiceService.java
> [#32]feat:실시간 채팅, 음성 파일 업로드 기능

- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/repository/PostRepository.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
> feat: 상대방의 게시글 불러오는 로직 변경

- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/controller/CommentController.java
- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/domain/ChatRoom.java
- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/domain/Post.java
- src/main/java/com/sparta/bluemoon/dto/ChatRoomResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/request/CommentRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/response/CommentResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostMyPageResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostOtherOnePostResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/UserInfoDto.java
- src/main/java/com/sparta/bluemoon/repository/CommentRepository.java
- src/main/java/com/sparta/bluemoon/repository/PostRepository.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/CommentService.java
- src/main/java/com/sparta/bluemoon/service/GoogleLoginService.java
- src/main/java/com/sparta/bluemoon/service/KakaoLoginService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
postId, commentId, roomId 등의 아이디값을 랜덤 문자열로 바꿔줍니다.
> [#39]feat:UUID

- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/dto/response/PostResponseDto.java
실시간 채팅, 음성 파일 업로드 코드를 리팩토링 합니다.
> [#32]refactor:실시간 채팅, 음성 파일 업로드 기능

- src/main/java/com/sparta/bluemoon/controller/CommentController.java
- src/main/java/com/sparta/bluemoon/controller/PostController.java
- src/main/java/com/sparta/bluemoon/domain/ChatRoomUser.java
- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/dto/CommentDto.java
- src/main/java/com/sparta/bluemoon/service/CommentService.java
> [#32]feature:실시간 채팅, 음성 파일 업로드 기능

- src/main/java/com/sparta/bluemoon/BluemoonApplication.java
- src/main/java/com/sparta/bluemoon/Scheduler.java
- src/main/java/com/sparta/bluemoon/domain/User.java
- src/main/java/com/sparta/bluemoon/dto/response/MainPostForAnonymousResponseDto.java
- src/main/java/com/sparta/bluemoon/exception/Exception.java
- src/main/java/com/sparta/bluemoon/exception/ExceptionHandling.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/security/filter/JwtAuthFilter.java
- src/main/java/com/sparta/bluemoon/security/provider/JWTAuthProvider.java
- src/main/java/com/sparta/bluemoon/service/CommentService.java
- src/main/java/com/sparta/bluemoon/service/PointService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/service/VoiceService.java
> [#49]refactor:중복로그인방지 코드 리팩토링

- src/main/java/com/sparta/bluemoon/controller/ChatController.java
- src/main/java/com/sparta/bluemoon/dto/response/UserInfoDto.java
- src/main/java/com/sparta/bluemoon/security/filter/JwtAuthFilter.java
> [#53]feat:유저 정보 조회시 포인트 같이 내려주기

- src/main/java/com/sparta/bluemoon/controller/CommentController.java
- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/dto/request/CommentRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/request/PostCreateRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/response/CommentResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/UserInfoDto.java
- src/main/java/com/sparta/bluemoon/service/CommentService.java
- src/main/java/com/sparta/bluemoon/service/GoogleLoginService.java
- src/main/java/com/sparta/bluemoon/service/KakaoLoginService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/service/UserService.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginService.java
> [#35] refactor: 포인트 생성 시점 변경

- src/test/java/com/sparta/bluemoon/service/UserServiceTest.java
> [#58]test:UserService test Code 작성

- src/main/java/com/sparta/bluemoon/repository/UserRepository.java
- src/test/java/com/sparta/bluemoon/service/PointServiceTest.java
- src/test/java/com/sparta/bluemoon/service/PostServiceTest.java
> [#48] test: 포스트 테스트코드

- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
> [#63] feat: 채팅방 이전 메시지 불러오기

- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/repository/ChatMessageRepository.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
> [#69] feat: 채팅 메세지 순서 수정

- src/main/java/com/sparta/bluemoon/controller/ChatController.java
- src/main/java/com/sparta/bluemoon/domain/Alarm.java
- src/main/java/com/sparta/bluemoon/domain/ChatMessage.java
- src/main/java/com/sparta/bluemoon/domain/ChatRoom.java
- src/main/java/com/sparta/bluemoon/dto/ChatMessageDto.java
- src/main/java/com/sparta/bluemoon/repository/AlarmRepository.java
- src/main/java/com/sparta/bluemoon/repository/ChatRoomRepository.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/ChatService.java
- src/test/java/com/sparta/bluemoon/service/PointServiceTest.java
> [#71]feat:채팅메세지, 알람 기능

- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
> [#74] 채팅방 uuid

- src/main/java/com/sparta/bluemoon/controller/ChatController.java
- src/main/java/com/sparta/bluemoon/dto/ChatMessageDto.java
- src/main/java/com/sparta/bluemoon/repository/ChatRoomRepository.java
- src/main/java/com/sparta/bluemoon/repository/ChatRoomUserRepository.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/ChatService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/service/UserService.java
> [#80]refactor:토큰에서 BEARER 제거

- build.gradle
- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/domain/Alarm.java
- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/domain/Post.java
- src/main/java/com/sparta/bluemoon/dto/ChatMessageDto.java
- src/main/java/com/sparta/bluemoon/dto/CommentDto.java
- src/main/java/com/sparta/bluemoon/dto/request/ChatRoomOtherUserInfoRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/request/CommentRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/request/PostCreateRequestDto.java
- src/main/java/com/sparta/bluemoon/dto/response/AlarmResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/ChatRoomOtherUserInfoResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/MessageResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostCreateResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostOtherOnePostResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostResponseDto.java
- src/main/java/com/sparta/bluemoon/exception/ErrorCode.java
- src/main/java/com/sparta/bluemoon/exception/ExceptionHandling.java
- src/main/java/com/sparta/bluemoon/repository/CommentQuerydslRepository.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/ChatService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
- src/main/java/com/sparta/bluemoon/service/RedisSubscriber.java
- src/main/java/com/sparta/bluemoon/util/Calculator.java
- src/test/java/com/sparta/bluemoon/service/CommentServiceTest.java
> [#121]feat:채팅방 입장시 상대유저 정보 확인

- src/main/java/com/sparta/bluemoon/domain/Comment.java
- src/main/java/com/sparta/bluemoon/dto/CommentDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostOtherOnePostResponseDto.java
- src/main/java/com/sparta/bluemoon/dto/response/PostResponseDto.java
- src/main/java/com/sparta/bluemoon/security/jwt/JwtDecoder.java
> [#153]bugfix:22-05-13

- src/main/java/com/sparta/bluemoon/config/RedisRepositoryConfig.java
- src/main/java/com/sparta/bluemoon/controller/AlarmController.java
- src/main/java/com/sparta/bluemoon/dto/response/AlarmDto.java
- src/main/java/com/sparta/bluemoon/repository/AlarmRepository.java
- src/main/java/com/sparta/bluemoon/service/AlarmService.java
> [#172]feat:알람메세지 가져오기

- src/main/java/com/sparta/bluemoon/config/handler/StompHandler.java
- src/main/java/com/sparta/bluemoon/controller/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/domain/Alarm.java
- src/main/java/com/sparta/bluemoon/dto/response/AlarmDto.java
- src/main/java/com/sparta/bluemoon/dto/response/SocialLoginResponseDto.java
- src/main/java/com/sparta/bluemoon/security/WebSecurityConfig.java
- src/main/java/com/sparta/bluemoon/service/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/service/ChatService.java
- src/main/java/com/sparta/bluemoon/service/PostService.java
알람 메세지 리스폰스 변경 및 채팅 리스트 불러오기 버그 픽스
> [#177]bugfix:알람 메세지 리스폰스 변경 및 채팅 리스트 불러오기

- src/test/java/com/sparta/bluemoon/service/PostServiceTest.java
> [#182]test:postService test code

- src/test/java/com/sparta/bluemoon/service/AlarmServiceTest.java
> [#185]test:AlarmService Test code

- src/test/java/com/sparta/bluemoon/service/ChatRoomServiceTest.java
ChatRoomService Test code를 작성합니다
> [#189]test:ChatRoomService Test code

- src/main/java/com/sparta/bluemoon/chatRoom/ChatRoomController.java
- src/main/java/com/sparta/bluemoon/chatRoom/ChatRoomService.java
- src/main/java/com/sparta/bluemoon/comment/CommentService.java
- src/main/java/com/sparta/bluemoon/lot/LotService.java
- src/main/java/com/sparta/bluemoon/point/PointRepository.java
- src/main/java/com/sparta/bluemoon/point/PointService.java
- src/main/java/com/sparta/bluemoon/post/PostController.java
- src/main/java/com/sparta/bluemoon/post/PostService.java
- src/main/java/com/sparta/bluemoon/post/requestDto/PostCreateRequestDto.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginService.java
- src/main/java/com/sparta/bluemoon/user/User.java
- src/main/java/com/sparta/bluemoon/user/UserController.java
- src/main/java/com/sparta/bluemoon/user/UserRepository.java
post save 추가 및 userRepository fetch join 추가
> refactor:postService

- src/main/java/com/sparta/bluemoon/BluemoonApplication.java
- src/main/java/com/sparta/bluemoon/user/KakaoLoginService.java
> feat:timeZone

- src/main/java/com/sparta/bluemoon/chat/ChatController.java
> refactor:alarm save

- src/main/java/com/sparta/bluemoon/comment/CommentController.java
- src/main/java/com/sparta/bluemoon/comment/requestDto/CommentRequestDto.java
- src/main/java/com/sparta/bluemoon/exception/ErrorCode.java
- src/main/java/com/sparta/bluemoon/post/requestDto/PostCreateRequestDto.java
댓글 저장시 글과 보이스가 둘다 입력되지 않았을 경우 에러 발생
> refactor:commentSaveError

- src/main/java/com/sparta/bluemoon/comment/responseDto/CommentResponseDto.java
> refactor:timer

- src/main/java/com/sparta/bluemoon/lot/LotController.java
- src/main/java/com/sparta/bluemoon/lot/LotService.java
- src/main/java/com/sparta/bluemoon/point/Point.java
- src/main/java/com/sparta/bluemoon/point/PointService.java
- src/main/java/com/sparta/bluemoon/test/NaverLoginService.java
- src/main/java/com/sparta/bluemoon/user/GoogleLoginService.java
- src/main/java/com/sparta/bluemoon/user/KakaoLoginService.java
- src/main/java/com/sparta/bluemoon/user/UserController.java
- src/main/java/com/sparta/bluemoon/user/UserService.java
- src/main/java/com/sparta/bluemoon/user/responseDto/UserInfoDto.java
> [#255]feat:recommendCount
